server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**

  security:
    user:
      name: test@naver.com
      password: 1q2w3e4r!
    oauth2:
      client:
        registration:
          google:
            clientId: 177934033945-rs7d2k17hba5pol7m4e3os2e11umh3r8.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
          naver:
            clientId: E0hshZg2uSvqXbN2sSEu
            clientSecret: auPM06AQ0j
            scope:
              - email
              - name
            clientName: Naver
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8000/login/oauth2/code/naver
        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response


  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-2.ckgdwsl9oa5b.ap-northeast-1.rds.amazonaws.com:3306/stussy-20220930
    username: admin
    password: 1q2w3e4r

mybatis:
  mapper-locations:
    - /mappers/*.xml
